basic_settings:
  site_title: Sermonis.AI
  # favicon_image: /assets/img/favicon.png

header_settings:
  logo_image: /assets/img/brand/blue_on_alpha.png
  mobile_logo_image: /assets/img/brand/purple_on_alpha.png
  # Choose a color for your header [blue, dark, light].
  theme: light
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "no"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
      # submenu_items:
      # - title: Landing Page
      #   url: /
      #   icon: ni-spaceship text-success    
      # - title: Blog
      #   url: /blog
      #   icon: ni-books text-primary
      # - title: 'Features'
      #   url: '/features'
    - title: 'Use Cases'
      url: '/use_cases'     
    - title: Pricing
      url: /pricing        
    - title: 'Blog'
      submenu_items:
      - title: Blog
        url: /blog
        icon: ni-books text-primary
    #   - title: Narrow Grid Example
    #     url: /blog-narrow-example
    #     icon: ni-align-center text-success
    #   - title: Wide Grid Example
    #     url: /blog-grid-example
    #     icon: ni-image text-info
    #   - title: List Example
    #     url: /blog-list-example
    #     icon: ni-bullet-list-67 text-default    
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

footer_settings:
  footer_tagline: Sermonis.AI. Translating code into conversation.

contact_settings:
  form_action: 'https://formspree.io/f/xknkgpyv'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/sermonisai'
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: 'https://www.github.com/sermonisai'
  reddit_url: ''
  linkedin_url: 'https://www.linkedin.com/company/sermonis-ai'

authors:
  Akinwande:
    name: Akinwande Lalude
    picture: /assets/img/faces/team-1.jpg
  Alexandra:
    name: Alexandra Frank 
    picture: /assets/img/faces/team-4.jpg
  Devin:
    name: Devin Hollier 
    picture: /assets/img/faces/michael.jpg
  Ebenge:
    name: Ebenge Usip
    picture: /assets/img/faces/michael.jpg

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 